### ISSUE TITLE
Unable to get PID

### ISSUE THREAD

**Issue by ianwinter** [GetiPlayerAutomator/get-iplayer-automator#458]
Hi, I'm using 1.8.4 on Yosemite and if I use "Current Webpage" option, it puts the entry in the queue but doesn't populate the PID after "Process PID" and won't download. The shows that come back in the search work OK, but, from "Current Webpage" don't - can you get the PID manually?

**Comment by dinkypumpkin** [comment]
Cannot reproduce.  Give an example URL.  

You can copy the PID from the iPlayer episode URL in your browser address field.

**Comment by ianwinter** [comment]
http://www.bbc.co.uk/iplayer/episode/b00v3761/chuggington-series-2-13-heave-ho-harrison

The PID in the app shows as b00v3761 and if I "process PID" it doesn't change.

**Comment by dinkypumpkin** [comment]
The PID for your first example won't change.  It's more than 7 days since last broadcast, so not in the programme cache, so can't be converted to an integer index.  The opposite is true of your second example.  As long as the Status column says "Available", it should be available for download, assuming it isn't screwed up by proxy problems.
