### ISSUE TITLE
GiA no longer downloads HD video for BBC shows

### ISSUE THREAD

**Issue by perambulare** [GetiPlayerAutomator/get-iplayer-automator#464]
If you try and download any video in HD from iPlayer, it attempts to do so, but then either fails (if you haven't specified another format) or falls back to a lower quality format. This seems to have started on the 29th of January. 

I am not sure if this has anything to do with it, but I installed MacOS's Security Update 2015-001, Safari 7.1.3, and Remote Desktop Client Update the previous evening. I am running MacOS 10.9.5, and GiA 1.8.4. I'm using a DNS proxy ([Ad-Free-Time](http://adfreetime.com)).

**What steps will reproduce the problem?**
Attempt to download any video with "Flash HD" selected as the top entry in the "BBC Formats" -> "BBC TV Show Formats" section of preferences. 

**What is the expected output? What do you see instead?**
Expect to see an HD program, but I see a lower resolution program. 

**What version of GiA are you using? On what version of OS X?**
I am running MacOS 10.9.5, and GiA 1.8.4.

**What programme are you attempting to download (full title, series and episode)?**
This happens with all of them, but for the purposes of this report, I will use two examples: 
[The Graham Norton Show](http://www.bbc.co.uk/iplayer/episode/b051c7m2/the-graham-norton-show-series-16-episode-16) Series 16, Episode 16.
[Food & Drink](http://www.bbc.co.uk/iplayer/episode/b05121t7/food-drink-series-3-5-more-for-less) Series 3, Episode 5.

Reason I'm providing two is that Food & Drink fails almost immediately, and downloads the next lowest format. Graham Norton downloads a huge chunk of the HD version, then fails right at the end and switches to the lower resolution.

**If you cannot download a programme, provide a verbose log of the attempt (see Verbose Log in wiki).**
[Log for Graham Norton](http://pastebin.com/RihZfK14)
[Log for Food & Drink](http://pastebin.com/K8Wwhtkm)

**Please provide any additional information below.**
Using Ad-Free-Time and I noticed this problem started the day after updating MacOS with a security patch, and Safari. Also: thanks for your work on GiA. Very much appreciated.

**Comment by larryyaeger** [comment]
I suspect something has changed with iPlayer servers, as I'm having the same trouble but have not yet updated with the latest security patch, though I am also running Mac OS X 10.9.5 (and Safari 7.1.2).  HD downloads have completely stopped working.  BBC vhigh and ITV high SD downloads continue to work normally.  I'm using the default proxy.

**Comment by perambulare** [comment]
Yep, this is exactly what I'm seeing. Especially the behavior you mention about it starting and failing, or just immediately going to the very high.

**Comment by dinkypumpkin** [comment]
One CDN is blocking you because you are outside the UK.  The other is probably doing the same thing, though it appears as a different sort of error.  Either way, there is nothing GiA can do about it.

**Comment by dinkypumpkin** [comment]
@perambulare: Your log shows that you have some obsolete settings.  SeeL

https://code.google.com/p/get-iplayer-automator/wiki/BbcSwfUrl

**Comment by larryyaeger** [comment]
Excuse me, but this has nothing to do with being blocked because of being outside the UK.  Kind of the point of using a proxy, whether its adfreetime like the OP uses or GiA's default proxy like I'm using.  And the problem is affecting only HD content, not SD content, so it can't possibly be a generic block on the OP's or my IP addresses.  Despite all HD downloads being broken I can download anything in vhigh or high, as I previously stated.  All HD content is broken, no SD content is broken, the problem manifests on multiple releases of OS X, and on multiple versions of GiA.  I'm not an expert on this particular problem or this particular code, but I do code and can think logically.  Something appears to have changed in how HD streams are served that is breaking GiA.  If someone on the GiA team doesn't fix it, it's probably going to stay broken.  Please reopen this and get it into the hands of the right person.  Thanks.
