### ISSUE TITLE
BBC programme "Click - 20/06/15" will not download

### ISSUE THREAD

**Issue by brendau** [GetiPlayerAutomator/get-iplayer-automator#496]
What steps will reproduce the problem?
Trying to download BBC TV programmes.
What is the expected output? What do you see instead?
Download Failed
What version of GiA are you using? On what version of OS X?
version 1.8.5 (1735)
What programme are you attempting to download (full title, series and episode)?
Click 20/6/2015
If you cannot download a programme, provide a verbose log of the attempt (see Verbose Log in wiki).

[User did not follow [instructions](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Reporting-Issues) - logging spew [removed](https://gist.github.com/anonymous/b377087328b816c62bde)]

Please provide any additional information below.

Can you please advise how to fix the downloads.
Downloads from ITV  continue to operate perfectly.
Regards
James

**Comment by willson556** [comment]
Seems to be working fine on my end. Are you still experiencing this issue?

**Comment by brendau** [comment]
Yes, it happens with any BBC programmeGet iPlayer Automator 1.8.6 Initialized.

Updating Program Index Feeds from Server...
AppController: Index was Up-To-Date.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=410): Downloading Formula 1: 2015 - Highlights - Austrian
410:	Formula 1: 2015 - Highlights - Austrian, BBC One, , default
INFO: 1 Matching Programmes
INFO: Checking existence of default version
INFO: flashvhigh2,flashvhigh1,flashhigh2,flashhigh1,flashstd2,flashstd1 modes will be tried for version default
INFO: Trying flashvhigh2 mode to record tv: Formula 1: 2015 - Highlights - Austrian
INFO: File name prefix = Formula 1 2015 - Highlights - Austrian ((flashvhigh))                 
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to stream file /Users/James/Movies/TV Shows/Formula 1 2015/Formula 1 2015 - Highlights - Austrian ((flashvhigh)).partial.mp4.flv via RTMP
INFO: skipping flashvhigh2 mode
INFO: Trying flashvhigh1 mode to record tv: Formula 1: 2015 - Highlights - Austrian
INFO: File name prefix = Formula 1 2015 - Highlights - Austrian ((flashvhigh))                 
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 3 (raw code = 768)
WARNING: Failed to stream file /Users/James/Movies/TV Shows/Formula 1 2015/Formula 1 2015 - Highlights - Austrian ((flashvhigh)).partial.mp4.flv via RTMP
INFO: skipping flashvhigh1 mode
INFO: Trying flashhigh2 mode to record tv: Formula 1: 2015 - Highlights - Austrian
INFO: File name prefix = Formula 1 2015 - Highlights - Austrian ((flashhigh))                 
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to stream file /Users/James/Movies/TV Shows/Formula 1 2015/Formula 1 2015 - Highlights - Austrian ((flashhigh)).partial.mp4.flv via RTMP
INFO: skipping flashhigh2 mode
INFO: Trying flashhigh1 mode to record tv: Formula 1: 2015 - Highlights - Austrian
INFO: File name prefix = Formula 1 2015 - Highlights - Austrian ((flashhigh))                 
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 3 (raw code = 768)
WARNING: Failed to stream file /Users/James/Movies/TV Shows/Formula 1 2015/Formula 1 2015 - Highlights - Austrian ((flashhigh)).partial.mp4.flv via RTMP
INFO: skipping flashhigh1 mode
INFO: Trying flashstd2 mode to record tv: Formula 1: 2015 - Highlights - Austrian
INFO: File name prefix = Formula 1 2015 - Highlights - Austrian ((flashstd))                 
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to stream file /Users/James/Movies/TV Shows/Formula 1 2015/Formula 1 2015 - Highlights - Austrian ((flashstd)).partial.mp4.flv via RTMP
INFO: skipping flashstd2 mode
INFO: Trying flashstd1 mode to record tv: Formula 1: 2015 - Highlights - Austrian
INFO: File name prefix = Formula 1 2015 - Highlights - Austrian ((flashstd))                 
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 3 (raw code = 768)
WARNING: Failed to stream file /Users/James/Movies/TV Shows/Formula 1 2015/Formula 1 2015 - Highlights - Austrian ((flashstd)).partial.mp4.flv via RTMP
INFO: skipping flashstd1 mode
ERROR: Failed to record 'Formula 1: 2015 - Highlights - Austrian (b060f6c8)'
BBC Download (ID=410): Formula 1: 2015 - Highlights - Austrian Failed

AppController: Downloads FinishedI choose.
I have taken the Austrian GP highlights just now and it is the same result.

**Comment by dinkypumpkin** [comment]
Unless you can demonstrate that you're in the UK, then you're geo-blocked - your VPN or proxy has been rumbled.

**Comment by brendau** [comment]
This does not make sense because I can log in and watch BBC programmes live using my proxy.
I can also download to BBC iplayer no problem.
It is only using Get iplayer automator that there appears a problem.

**Comment by willson556** [comment]
There must be some issue with the way your proxy is configured that GiA isn’t picking it up. What type of proxy are you using and how is it configured?

**Comment by dinkypumpkin** [comment]
It makes perfect sense because GiA accesses streams differently than your browser.  You should have started by reading #483 - this issue has already been thrashed out.  GiA is picking up your proxy, or else it wouldn't even attempt a download.  But the proxy only gets you the stream location - you're still blocked by the server when you attempt to download.

**Comment by larryy** [comment]
I'm not sure #483 would have cleared the matter up for most people before, though hopefully it will now.  I just added some information about the difference between GIA's (and GiP's) HTTP routing and rtmpdump's SOCKS4 routing that gets at the underlying issue.  It's done in the context of explaining why the proxied-VPN solution fails for SD, but a whole-machine VPN solution works.  However, I think that difference comes into effect here as well.  I'm sure @dinkypumpkin and @willson556 know all this, but they're so familiar with it they might not have thought to explain it.  @vangelis66 clued me in via email.

That said, the OP's question still has merit...  If the browser can stream via HTTP and work with a proxy, why can't GiP/GiA/rtmpdump?  (Assuming that's really the salient difference.)

**Comment by dinkypumpkin** [comment]
For future readers: rtmpdump can use SOCKS, but it does not by default.  That wouldn't make sense.

HTTP proxying has nothing to do with RTMP streaming.  They are different protocols, so don't confuse the issue. The OP gave no clue what kind of VPN or proxy setup s/he was using.  Maybe it was one of the DNS redirectors that only provides iPlayer access via browser.  Who knows?  It doesn't matter.  If rtmpdump connections do not come from UK by whatever means, the CDNs will block access to those TV streams.  That was made clear by both you and @mostlyotter in #483.  HTTP proxies are irrelevant here,  so if whatever VPN arrangement the OP uses doesn't route RTMP traffic through the UK, s/he will need to find one that does.

**Comment by larryy** [comment]
When watching in a browser, what streaming protocol is used?  HTTP?  RTMP?  SOCKS?

**Comment by Vangelis66** [comment]
@brendau wrote: 

> ... I can log in and watch BBC programmes live using my proxy.
> I can also download to BBC iplayer no problem.

Live BBC TV streaming in a browser (e.g. Mozilla Firefox) through 
the Adobe Flash Player plugin is done over HTTP with
a delivery method called "Adobe HDS" - that is why your 
HTTP proxy in a browser works for "LIVE" TV. 
The Beeb's app "BBC iPlayer Downloads", which downloads 
DRM'ed MP4 files to your computer for later (off-line?) viewing 
also uses HTTP to fetch both files and DRM lic, so yet again 
your proxy works...

> It is only using Get iplayer automator that there appears a problem.

The catch-up TV files (VOD) are streamed by default over RTMP; 
as @dinkypumpkin and myself have already explained 
(e.g. https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues/483#issuecomment-114709586) 
HTTP proxying will get you as far as the "door" of a 
Flash Media Server - then it depends on the server's configuration 
if you're allowed to step in...
Currently all CDN servers hosting SD quality variants (flashvhigh and lower)
are geo-blocked, hence your inability to fetch...
Try to download the flashhd mode of "Click 20/06/2015" (pid=b05z15th); 
this should work with a UK HTTP proxy...

If your proxy has enough available bandwidth and small latency 
(this is not the case with the "free" ones found on-line), you can try the standalone 
get_iplayer script (now in tag 2.94) to grab SD VOD BBC, but instead of 
the flashmodes you should go for the hls modes - these use a 
streaming method called Apple HLS exclusively over HTTP!
The download is done via ffmpeg (which has to be proxied), 
not rtmpdump which lacks HTTP support...

<code>get_iplayer -p "http://proxyhost:proxyport" --pid=b05z15th --tvmode=hlsvhigh --force</code>

worked fine for me with a somewhat reliable open HTTP proxy...

**Comment by mostlyotter** [comment]
A small point, but Click 20-06-2015 can also be downloaded by GiA in flashlow. (Flashlow has the same audio bitrate as flashhd, but less than 20% of the video bitrate.)

**Comment by brendau** [comment]
Thanks for the advice.
I will try and let you know.
