### ISSUE TITLE
GiA is "flaky" after update to 1.8.6

### ISSUE THREAD

**Issue by larryy** [GetiPlayerAutomator/get-iplayer-automator#497]
Since updating GiA to 1.8.6 I have seen two types of flaky, intermittent behavior.  Either could be due to the source, but there are two different sources and the timing would be highly coincidental.

The first, most problematic, and, IMO, mostly likely to be due to the underlying update to GiP is that downloads will randomly fail, then succeed on second, or third, or fourth attempt.  I wonder if the logic for choosing the CDN has changed.  When downloading from the BBC I always download HD content, with a commercial VPN connection via proxy for GiA's initial HTTP connection, and a direct connection for the subsequent RTMP streaming.  I believe it's the RTMP streaming that is failing, and I'm guessing it's because GiP is now randomly selecting the geo-blocked CDN when it formerly did not.  But whatever the actual diagnosis, GiA now fails randomly for BBC HD content, when it formerly did not.

The second issue is just weird, but also intermittent.  I'm downloading each weekday's episode of Heartbeat from ITV.  For a long time this has yielded files with a 704x396 resolution.  The day I enabled the new Flash - HD format, that only came with the current release, the first episode I downloaded had a resolution of 896x504.  Not exactly HD, but a pleasantly higher resolution.  The next day, however, it went back to 704x396.  The day after that, 896x504.  And it has actually toggled back and forth every day for 6 downloads (a week and a day, by the calendar), except for one day when it downloaded with a resolution of 512x290, and looked as much worse as one might expect.  I discarded that file, removed its entry from the download_history file, re-downloaded, and this time got 896x504.  It seems as if GiA/GiP is downloading random resolutions.  (I have now removed anything below Flash - High, to hopefully prevent it from backing off down to resolutions that are pretty much unwatchable for me.)

Random CDNs and random resolution choices seem to have come with the new release, if I'm interpreting what is going on correctly.  But whatever is causing it, it's a significant regression from the previous version.  In fact, since I use the quick cached listings anyway, I'm probably going to revert to the previous release, but thought I should report this.  FWIW, over on the GiP mailing list (on infradead.org), a new thread "Random stalling" reports what I suspect is the same underlying issue with randomly failing downloads, and another new thread "Can't get Episode 3 of 'The Art of Germany'" reports a failed download that multiple other people have said downloaded for them just fine.  I think there's a theme.

**Comment by larryy** [comment]
One extra tidbit, I removed the most recent 704x396 episode (from the filesystem and the download_history file), removed the "Flash - High" option, retaining only "Flash - HD", and tried to re-download the episode, to see if it would get the HQ 896x504 version.  It didn't.  It failed, saying none of the modes I specified were available.  So the second bit of flakiness may be down to ITV and its CDN.  Do they use more than one CDN?  If so, might one have HQ and the other not?  Would GiA/GiP switch CDNs if the specified mode was not available on the first?

**Comment by dinkypumpkin** [comment]
Nothing has changed with BBC CDN selection in get_iplayer.  CDN priority is specified dynamically in the stream data from the BBC, which get_iplayer respects. They may be rotating more now - no way to know.  Either use a full VPN or configure the embedded get_iplayer to exclude all Akamai streams.  This is not a problem with GiA or get_iplayer.

Not every ITV programme will have the same resolutions available.  Some will have no better than  704x396 available, and a few not even that.  Some older programmes won't have the higher resolutions available for newer programmes  You'll have to look at the metadata in the verbose log for specific episodes to know what streams are available in order to determine if something is going wrong in GiA.  There might still be a problem with the new ITV metadata, but without specific episodes to check there is no way to even guess.  Create a new issue if you want to pursue this with information for a specific episode that I can test.

There is no CDN selection with ITV.

Any "random stalling" stems from time- or location-dependent network/server problems.  There is nothing GiA or get_iplayer can do about it.. The network problems of one person in one location are just that, as acknowledged by the author of the mailing list thread you referenced.  One-off failures like the 'The Art of Germany' are also usually meaningless. There are many upstream problems that can cause temporary download failures, but some people lack the patience to keep trying.  But even that was irrelevant in this case: that user posted to the mailing list while the programme was being broadcast, so the "failed" download was for a programme that wasn't yet available.
