### ISSUE TITLE
Error: "Problem Unknown" whilst downloading programme

### ISSUE THREAD

**Issue by gingerbeardman** [GetiPlayerAutomator/get-iplayer-automator#498]
What steps will reproduce the problem?
Put b05rc6ky into queue
Start downloads
Wait for error

What is the expected output? What do you see instead?
Unable to download

What version of GiA are you using? On what version of OS X?
GiA 1.8.5 and 1.8.6
on 10.10.3

What programme are you attempting to download (full title, series and episode)?
Trying to download: b05rc6ky
(Collectaholics, Series 2, Episode 8)

If you cannot download a programme, provide a verbose log of the attempt (see Verbose Log in wiki).

**USER DID NOT FOLLOW [INSTRUCTIONS](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Reporting-Issues) - LOGGING SPEW [REMOVED](https://gist.github.com/anonymous/b459a8541250685b0176)**

**Comment by dinkypumpkin** [comment]
Always check the iPlayer site before reporting an issue.  If you had, you would have seen that your programme is only available in a signed version, so you have to select Signed in preferences for it to download.

And next time, you would be well advised to follow the instructions for posting your log instead of dumping it in your issue report.

**Comment by gingerbeardman** [comment]
Thanks for the feedback.

I wasn't aware of the signed checkbox. Perhaps for this specific error the app could automatically download signed versions of they are the only version available? Or present a more descriptive error message as to what the user needs to change in settings.
