### ISSUE TITLE
"Problem Unknown" error when only signed version of programme exists and signed preference is not checked

### ISSUE THREAD

**Issue by gingerbeardman** [GetiPlayerAutomator/get-iplayer-automator#499]
*What steps will reproduce the problem?*
Try to download a programme where only a signed versions exists

*What is the expected output? What do you see instead?*
"Problem Unknown"

*What version of GiA are you using? On what operating system?*
GiA 1.8.5 and 1.8.6
on Mac OS X, 10.10.3

*What programme are you attempting to download (full title, series and episode)?*
b05rc6ky
(Collectaholics, Series 2, Episode 8)

*If you cannot download a programme, provide a verbose log of the attempt. 
See Verbose Log page in wiki for instructions on posting a verbose log with your issue report.*
https://gist.github.com/anonymous/b459a8541250685b0176

*Please provide any additional information below.*

Perhaps for this specific error the app could automatically download signed versions if they are the only version available? 

Or perhaps present a more descriptive error message than "Problem Unknown" as to what the user needs to change in app settings?

**Comment by dinkypumpkin** [comment]
Your log indicates you still don't have Signed selected in preferences.  Maybe it wasn't saved, though I couldn't say why.  Try restarting GiA after selecting Signed.

Also, stop posting logs from 1.8.5.  If you really have upgraded to 1.8.6, post logs from it.

**Comment by gingerbeardman** [comment]
This log is to show the behaviour of the app (ie. not very usable) when when signing is not checked and only a signed version of the programme is available.

Of course I can select signed and have the programme download, but that's not what this issue is about.

I'm trying to help you make the app more accessible and easier to use for people who don't know its internals (pretty much everybody but you, it seems).

**Comment by dinkypumpkin** [comment]
So ticking a checkbox in preferences is "internals"?  GiA works the way it does because get_iplayer works that way, and it is very unlikely to change.  Even if it did change, your notion brings its own complications.  Should only the signed version be automatically downloaded?  Or only the audio described version?  What if both are available?  You'd still need options for a user to indicate those preferences, plus additional options for users to disable automatic downloading of alternate versions lest - as has happened in the past - they are confused by signing or audio description appearing where they don't expect it.

I'll leave this tagged as an enhancement request since it wouldn't be a bad idea to have a more specific error message if that is somehow possible.

**Comment by CorrieFan** [comment]
I'm getting the following message trying to download some ITV programs:

Provided proxy could not be retrieved.
Downloads may fail.
Do you wish to continue?

**Comment by gingerbeardman** [comment]
@dinkypumpkin you are sure making my task of trying to help very hard work.

But I do think we've reached a good conclusion, your acceptance of my suggestion of a more friendly error message. Cheers

**Comment by approtech** [comment]
Just a comment; I'm using 1.8.6 and there is no help in the Preferences panel to indicate what happens if the 'Signed' or 'AD' checkboxes are or are not ticked. So an otherwise-uninformed user cannot tell whether this means 'Allow if ticked' or 'Prefer if ticked' or (as appears to be the case) 'Don't download if unticked, even if it's the only version available'. I still have no idea how (or if?) a user would force GiA to download a signed version if it was NOT the only version available. The suggested enhancement is certainly sensible, and appropriate - the current error message is untrue: it's not really an unknown problem, except to the poor user. For many of us a signed version is not what is wanted, but if it's the ONLY version available of an interesting programme, it's better than nothing.

**Comment by NumptyKnackers** [comment]
Ah yes. I'm think I'm having this problem while trying to get this programme: http://www.bbc.co.uk/iplayer/cbeebies/episode/b021t02m/ad/octonauts-the-mariana-trench-adventure

A standard version isn't available I'm guessing...

**Comment by AllenLW** [comment]
It has been many, many, many weeks since I have been able to downloaded anything from BBC or ITV sites using Get iPlayer v. 1.8.6. Always get a "download failed" message in one form or another with a "report problem" message of some kind. I can't believe I am the only one having this problem. What useful suggestions are there to remedy this fatal problem?

**Comment by CorrieFan** [comment]
GIA hasn't worked for me all month. "Timed out" and "bad proxy" in every case.

**Comment by dinkypumpkin** [comment]
Closed by 5fad141a712125c729c9e4414d48007db172592b
