### ISSUE TITLE
App hangs on converting ITV programmes in El Capitan (Version 1.8.6 (1741))

### ISSUE THREAD

**Issue by sheepworrier** [GetiPlayerAutomator/get-iplayer-automator#522]
Downloads all shows successfully into a usable FLV at the end of the process (I convert in Handbrake to MP4), but GIA hangs on converting to MP4 for every file.  If I have a large queue of files, I have to workaround by clicking Stop, Permanently Skip Selected Series-Link Entries; Start; then convert the FLV in Handbrake. I suspect this is an issue with my configuration (on a new Mac) rather than a bug, but can't see anything obvious in the log:

AppController: Starting Downloads

Downloading Show 1/20:

ITV Download (ID=100812): Downloading The X Factor - Sun 01 Nov 2015
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
INFO: Metadata processed.
INFO: Requesting programme data.
INFO: Program data processed.
INFO: Launching RTMPDUMP...
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
WARNING: HandShake: Type mismatch: client sent 6, server answered 8
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO:   duration              2831.76
INFO:   moovPosition          32.00
INFO:   width                 896.00
INFO:   height                504.00
INFO:   videocodecid          avc1
INFO:   audiocodecid          mp4a
INFO:   avcprofile            100.00
INFO:   avclevel              31.00
INFO:   aacaot                2.00
INFO:   videoframerate        25.00
INFO:   audiosamplerate       48000.00
INFO:   audiochannels         2.00
INFO: trackinfo:
INFO:   length                70792.00
INFO:   timescale             25.00
INFO:   language              und
INFO: sampledescription:
INFO:   sampletype            avc1
INFO:   length                135924736.00
INFO:   timescale             48000.00
INFO:   language              und
INFO: sampledescription:
INFO:   sampletype            mp4a
ERROR: RTMP_ReadPacket, failed to read RTMP packet header
INFO: Connection timed out, trying to resume.
Resuming download at: 433548.473 kB
ITV Download (ID=100812): RTMPDUMP finished
INFO: Converting FLV File to MP4
ffmpeg version 1.2.1 Copyright (c) 2000-2013 the FFmpeg developers
  built on Jun 18 2013 00:18:40 with gcc 4.2.1 (GCC) (Apple Inc. build 5666) (dot 3)
  configuration: --prefix=/Volumes/Ramdisk/sw --as=yasm --disable-shared --enable-static --disable-ffplay --disable-ffprobe --disable-ffserver --enable-pthreads --enable-runtime-cpudetect --enable-filters --enable-postproc --enable-vda --enable-bzlib --enable-zlib --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libspeex --enable-libtwolame --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libxavs --enable-gpl --enable-libx264 --enable-libxvid --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libfreetype --enable-fontconfig --enable-libass --enable-librtmp --enable-libschroedinger

ITV Download (ID=100812): Download Cancelled

**Comment by dinkypumpkin** [comment]
If it's really hanging, you're unlikely to get much help from the log.  If your output directory is on an external disk or network drive, change it to a location on your internal disk and see if that helps. If that doesn't apply, you should run the remux outside GiA to see if any useful error messages appear.  From the prompt:

    "/Applications/Get iPlayer Automator.app/Contents/MacOS/ffmpeg" -i file.flv -acodec copy -vcodec copy -y file.mp4

**Comment by sheepworrier** [comment]
Thanks for the swift reply.  I used the line above to successfully remux the latest show that was hanging, then set GIA starting again on the remaining queue.  GIA successfully converted "The Hunt - The Hardest Challenge" (1128) without hanging, but then hung again on the next item "Jekyll & Hyde - Episode 1 - The Harbinger" (100331).

One common thread here is the shows that GIA is unable to convert internally are all ITV shows, whereas it was able to successfully convert the BBC show.  Would that possibly be the root cause of the issue?

**Comment by dinkypumpkin** [comment]
Probably no coincidence, since ITV downloads are handled differently.  Whatever it is, it isn't reproducible. Suggestions:
- Select Verbose in preferences to see if any other ffmpeg output is captured in the log.  
- Although the problem doesn't appear to be with ffmpeg, you may want to test with lower video quality settings for ITV to see if it makes a difference.  
- In your original report, the download was interrupted - see if that is a common thread for files that fail to remux. File corruption could be at fault, but that is also unlikely in this context.
- When GiA hangs use `pgrep` to check if ffmpeg is actually still running or whether it has in fact died.  If it's dying, you could get a more recent build of ffmpeg and temporarily swap with the embedded version referenced above.  It shouldn't be necessary, but perhaps worth testing as a last resort.

In the absence of a solution, you should:
- Make it a habit to position BBC programmes at the beginning of your queue so that they all complete before any problematic ITV programmes are processed.
- Use ffmpeg for remuxing as above.  You're wasting time and CPU re-encoding with Handbrake.

**Comment by sheepworrier** [comment]
It's not an issue with spaces is it?  On the next failed conversion, I've identified that the ffmpeg command that GiA is running is as follows:

`ps -ef | grep ffmpeg`
`  501 34761 34690   0  1:22pm ??         0:00.00 /Applications/Get iPlayer Automator.app/Contents/MacOS/ffmpeg -i /Users/djp42/Movies/iPlayer/Downton Abbey/Downton Abbey - Episode 8.partial.flv -vcodec copy -acodec copy /Users/djp42/Movies/iPlayer/Downton Abbey/Downton Abbey - Episode 8.mp4`

If I copy that command and run it in Terminal then it falls over with the error:

`-bash: /Applications/Get: No such file or directory`

However, putting the ffmpeg command, input and output in double quotes then it works.

**Comment by dinkypumpkin** [comment]
Not a spaces issue - otherwise GiA would never work for any one. Quotes only needed for shell evaluation.

**Comment by stickenhoffen** [comment]
I see the same thing, I think it's related to El Capitan.

**Comment by dinkypumpkin** [comment]
Possibly, but then you might expect it to occur for every programme, or at least every ITV programme, but according to the OP that isn't the case, nor does s/he indicate if El Capitan is used. This is where swapping in a more recent build of ffmpeg may be instructive.  The provided ffmpeg necessarily depends on a few system libraries, so I suppose it's possible some incompatibility has emerged in El Capitan, but whatever it is only affects certain FLV files downloaded from ITV.

**Comment by sheepworrier** [comment]
I'm on El Capitan (brand new machine) and it was occurring for every single ITV programme.
I swapped in the latest version of ffmpeg and initially saw no difference.  However, after a restart it then started spontaneously working.
The first remux (and subsequent tagging) within GiA took absolutely ages, but it did work and now is back to normal speed for all ITV programmes since.

**Comment by larryy** [comment]
FYI, I'm still on 10.10 (Yosemite) and now experiencing this problem.  Last week everything was fine.  All ITV programs I tried downloaded fine.  This week, I can't get the first one.  The shows, both last week's and this, are all Heartbeat, but I suspect that doesn't matter.

**Comment by dinkypumpkin** [comment]
Perhaps the ITV streams are at fault after all, but I can't reproduce on Yosemite (no El Capitan here). As above, swap in a newer ffmpeg and see if it works.

**Comment by sheepworrier** [comment]
Just had my first ITV failure since updating ffmpeg on the Almost Married film

**Comment by larryy** [comment]
Sorry, false alarm on the Yosemite front.  I experienced what I said,and, in fact, had a batch of downloads that made it through all the BBC shows and failed in conversion on the first ITV show, so I was fairly sure I was experiencing the problem described here, but it turned out to be entirely a coincidence.  I was using a folder on a remote volume mounted on the machine doing the downloading as the destination folder for GiA.  Purely by coincidence something about that configuration began causing problems during conversion at the time GiA was converting that first ITV show.  I started a BBC show last night and found it had hung in the same fashion this morning.  So to test I just grabbed a BBC *and* an ITV show after pointing GiA to a local hard drive, and it worked just fine for both.  So in my case the problem appears to be a networked file system problem, not anything specific to GiA.

**Comment by larryy** [comment]
Hmm, it may not mean anything, and writing to a networked volume may make this a different, if not unique problem, but it occurs to me that remote machine was just upgraded to El Capitan, and using that networked volume *used* to work, before the upgrade.  It seems unlikely, but if El Capitan is actually to blame in my case it would mean simply having an El Capitan file system in the mix was sufficient to stimulate the problem, *without* it having to be the OS under which GiA was running.  Seems highly unlikely, and is probably just another coincidence, but that's what happened.

**Comment by dinkypumpkin** [comment]
Thanks for the followup. Using a network volume can cause ffmpeg to hang regardless of the OS used on client or server, so I wouldn't expect that problem to be specific to El Capitan. That's why I told the OP use an internal disk if needed.

**Comment by sheepworrier** [comment]
I'm using the latest pre-release build to workaround issue #547 and this is now working, i.e. converting ITV programmes on El Capitan without me having to manually run ffmpeg.

I don't think I used the "Use Current Webpage" functionality on ITV before this new build, so it may have always been working via that route?
