### ISSUE TITLE
ITV download fails partway through

### ISSUE THREAD

**Issue by robincm** [GetiPlayerAutomator/get-iplayer-automator#528]
What steps will reproduce the problem?
Attempt to download Prey Episode 1 (ITV)
What is the expected output? What do you see instead?
Download fails partway through
What version of GiA are you using? On what version of OS X?
GiA  Version 1.8.6 (1741)       OS X 10.11.1
What programme are you attempting to download (full title, series and episode)?
Prey Series 2 Episode 1
[failure log.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/57913/failure.log.txt)

If you cannot download a programme, provide a verbose log of the attempt (see Verbose Log in wiki).

Please provide any additional information below.

**Comment by dinkypumpkin** [comment]
Cannot reproduce. Your log file doesn't show a failure, but GiA also discards some rtmpdump output.  You'll have to explain further what happened.

**Comment by robincm** [comment]
Hi Dinkypumpkin,
The download just fails at about 48 Mb, tries to restart (from the beginning) & fails again at much the same place!
Just tried again & it got to 87.4Mb!!
Sending a new log file
[Failure 2 log.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/58193/Failure.2.log.txt)

**Comment by dinkypumpkin** [comment]
it could be a problem at the ITV end, or it could just be poor connectivity from your location. It has happened before. Whatever it is, the problem is specific to your setup.  You can try an updated version of rtmpdump, but there is no guarantee it will help.

Download this: 

http://sourceforge.net/projects/get-iplayer/files/osx/utils/x86_64/20141227/get_iplayer-osx-utils-x86_64-20141227.zip

Make a backup copy of this:

/Applications/Get iPlayer Automator.app/Contents/Resources/rtmpdump-2.4

then replace it with `rtmpdump` from get_iplayer-osx-utils-x86_64-20141227.zip, renaming the file to `rtmpdump-2.4`

If GiA not installed in /Applications, adjust path accordingly

**Comment by robincm** [comment]
Thanks dinkypumpkin,
That worked a treat!! even tho' the dowloaded file is 6months older & 10 times the size of the version of rtmpdump that I had on my system!

Thanks again for all the effort you put in to help us mere mortals!

Best regards,
Robin

**Comment by dinkypumpkin** [comment]
Don't judge by the dates - it is newer code than GiA's rtmpdump. And don't judge by size - it is a static build of rtmpdump, while GIA's dynamically loads librtmp and other supporting libraries.

**Comment by erikmh** [comment]
I’d been having the same trouble as robincm, and had been assuming it was an on-going network issue here.

But the rtmp-dump you linked to above solves the problem here as well. Many thanks!
