### ISSUE TITLE
BBC Radio Downloads only Low Quality available

### ISSUE THREAD

**Issue by ogiles** [GetiPlayerAutomator/get-iplayer-automator#529]
Hi There
When i search for BBC Radio programmes i can see that the only download options available are the low quality ones.
I have all formats enabled in the preferences.
Is there another setting somewhere in the app?
Could this be a BBC issue?
Is anyone else experiencing this?

Thanks
Oli

**Comment by dinkypumpkin** [comment]
That is the expected behaviour if you are not in the UK or if your proxy/VPN has been rumbled by the BBC.  If you're in the UK, provide an example to test.

**Comment by ogiles** [comment]
Hi There
I am in the UK.
See attached screenshot for details.
Many thanks
Oli

**Comment by dinkypumpkin** [comment]
Upload your screenshot in the issue tracker.  Your email attachment didn't appear.

**Comment by ogiles** [comment]
Here you go
![screen shot 2015-12-10 at 11 48 46](https://cloud.githubusercontent.com/assets/16238702/11714706/0eb23f72-9f34-11e5-9c54-18178296193c.png)

**Comment by dinkypumpkin** [comment]
Cannot reproduce.  If you're using a proxyVPN in the UK you would have the same problem.  If not, read this:

https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Using-GiA-in-the-UK

If that doesn't apply, read this:

https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log

Instead of logging a download attempt, create a log while retrieving episode information.

**Comment by ogiles** [comment]
Hi 
Proxy = None  Seems to have fixed it.
Rings a bell from when i used it a year or two ago. I'll try to remember next time
Thanks very much for your help.

Oli
