### ISSUE TITLE
“PID” column in Download Queue should read “Index”?

### ISSUE THREAD

**Issue by erikmh** [GetiPlayerAutomator/get-iplayer-automator#531]
I’ve always used “Use Current Webpage” to queue shows, so I haven’t ever needed to pay attention to the meaning of the column marked “PID.”

In trying to work around the various ITV difficulties today, however, I tried using the `+` button and inputing a PID by hand — taking it from the “PID” field for the broadcast I wanted as listed in the itv.cache file. This consistently gave me an “Unknown: PID Not Found” error.

On a hunch, I tried the broadcast’s “Index” field — the first column in the itv.cache file. This worked perfectly, and I was able to process and download the correct broadcast.

Here’s the line in question from the itv.cache file. I first tried the PID (317074) and failed, but then used the index (100370) and succeeded.

```
#index|type|name|pid|available|episode|seriesnum|episodenum|versions|duration|desc|channel|categories|thumbnail|timeadded|guidance|web
...
100370|itv|Lewis|317074|Tue 17 Nov 2015|Tue 17 Nov 2015|||default||When a botanist accidentally digs up the body of the recently buried Murray Hawes, Lewis and Hathaway are set upon a seemingly impossible quest.|ITV Player|TV|http://www.itv.com/img/150x113/Lewis-a9f96130-a311-4eaa-b836-f97a3ea81dc3.jpg|1449969215||http://www.itv.com/CatchUp/Video/default.html?ViewType=5&amp;Filter=317074|
```

**Comment by dinkypumpkin** [comment]
Works fine here. Make sure you didn't get a leading or trailing space in the value you pasted in the PID field.

The PID field takes either PID or index as input. I don't know why, since the latter won't be known to GiA users unless they crack open the cache files. Use of index is really a get_iplayer thing. It might be slightly confusing when you see the input PID converted in-place to index value, but GiA uses the index value internally for BBC programmes. It's sort of a check the queued programme actually exists, I guess. ITV downloads work differently, but they have been adapted to the same cache model and UI actions, so they have PID and index as well.

**Comment by erikmh** [comment]
That is so strange. I’d tested it twice before deciding to post, and I typed it in manually *while* writing the post so that I could copy the exact error message. All three times it failed.

Works fine now, though. Thanks for the explanation, too, I appreciate it.
