### ISSUE TITLE
Use Current Webpage not working with ITV Hub

### ISSUE THREAD

**Issue by Grimfool** [GetiPlayerAutomator/get-iplayer-automator#555]
I have downloaded the pre release version 1.8.7-pre.2 (1753) onto my Macbook pro whilst here in the UK  and am unable to use the current web page facility with the ITV hub, see attachments. This seems very strange as I downloaded the same release version onto my Mac mini in the USA the other day and it works perfectly
[itv hub.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/223956/itv.hub.txt)
![screen shot 2016-04-18 at 3 23 38 pm](https://cloud.githubusercontent.com/assets/10996861/14607680/7c898d46-057a-11e6-86c0-15ed248b9e82.png)

**Comment by dinkypumpkin** [comment]
Thanks, but something went wrong. The .txt file only contains the page's URL, not the page's HTML source. Put the URL in your issue description and the HTML source in the .txt file.

**Comment by Grimfool** [comment]
Here's the HTML source
[ITV the durrells.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/224044/ITV.the.durrells.txt)

**Comment by dinkypumpkin** [comment]
I have no idea what happened there, but almost all the HTML disappeared for some reason. Let's begin again:

1. Open the Hub page in Safari
2. Invoke "Save As..." (Cmd-S)
3. In the Save dialog, make sure the Format selector reads "Page Source"
4. Click the Save button
5. Change the extension of the saved file from .html to .txt
6. Upload .txt file as attachment

**Comment by Grimfool** [comment]
Here you go
[The Durrells - Series 1 - Episode 3 - The ITV Hub.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/224064/The.Durrells.-.Series.1.-.Episode.3.-.The.ITV.Hub.txt)

**Comment by dinkypumpkin** [comment]
That's the ticket - thanks.

**Comment by UbiGit** [comment]
I live in the UK and this is the exact problem I've been experiencing since around 3rd Apr. GiPA cannot see any later programme schedules in the cache the last is _|itv|The Durrells|357021||357021|||default|||ITV Player|TV||1459492994|No Denton Code applied|http://www.itv.com/CatchUp/Video/default.html?ViewType=5&amp;Filter=357021|_ I have no idea what "_No Denton Code_" means.

10.11.5 Beta (15F18c) Mac mini (Late 2012) the GiPA error is the same on all my different Mac computers throughout the house.


[itv.cache.zip](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/224306/itv.cache.zip)

**Comment by dinkypumpkin** [comment]
@UbiGit - Stop with the thread hijacking. First you hijack #547 with the completely unrelated issue that Grimfool has kindly transferred to this thread. Now you hijack this thread with the completely unrelated issue that has already been covered in #547. Stop muddying the water.

**Comment by dinkypumpkin** [comment]
@Grimfool - Alas, differences in page content aren't the problem. GiA works fine with the page you provided. That is no surprise since the relevant parts are identical to the page rendered on my machines. My only other guess is that something is preventing GiA from executing javascript in Safari. You would get the same errors if javascript were disabled, for example, but then you should get a warning in the ITV pages. All I can suggest for the moment is to try "Use Current Webpage" with Chrome (remember to change preferences) to see if the problem occurs across browsers (GiA's method of access is much the same for both). Also try a few BBC pages to check if the problem occurs across sites.

**Comment by Grimfool** [comment]
Thanks for the investigation. I tried 'current webpage' with BBC and Safari worked OK. I then downloaded Chrome and used 'current webpage' with the ITV hub and it works OK, so I will continue to use Chrome for the ITV downloads until I return to the USA at the end of the month

**Comment by dinkypumpkin** [comment]
I thought that might be the case. Still, it doesn't shed any light on what aspect of your Safari installation disagrees with GiA where ITV pages are concerned. Perhaps you can compare with your other machine at a later date. However, since only 3 reports have surfaced, I suspect the root cause is something esoteric that may not have a work-around. The related bits of code are dead simple - there isn't much scope for changing them.

**Comment by dinkypumpkin** [comment]
@Grimfool - Redo your tests with new 1.8.7-pre.3 build. I took javascript out of the equation for Safari, so see if it makes a difference on your end. Perhaps a long shot, but worth checking.

**Comment by Grimfool** [comment]
Hi, I tried pre-release 3 with Safari and it was still the same. works OK with Chrome though

**Comment by dinkypumpkin** [comment]
OK, javascript wasn't the problem with Safari then. I guess that would have been too easy. Thanks for testing.

**Comment by GHubJames** [comment]
Hi DP, I see this ITV thing with interest: The first episode of the Durrells worked.
Now, no longer.
I've tried "use current webpage" - no luck. With Safari and Chrome as suggested.

Has there been a change at ITV and is registration with an email address required? Might that be the problem?
