### ISSUE TITLE
should the proxy be working?

### ISSUE THREAD

**Issue by hayesmaker** [GetiPlayerAutomator/get-iplayer-automator#559]
<img width="1358" alt="screen shot 2016-05-15 at 19 06 59" src="https://cloud.githubusercontent.com/assets/593429/15275293/3c951b5e-1ad0-11e6-8427-bbe84292b576.png">

**Comment by dinkypumpkin** [comment]
You appear to be in the UK, in which case you should have already read this:

https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Using-GiA-in-the-UK

If you are not in the UK, then you need to make your own arrangements You cannot rely on the provided proxy. Unfortunate, but true.

**Comment by hayesmaker** [comment]
So, if I'm not in the UK, and not using a proxy.. the there's still an issue

**Comment by larryy** [comment]
If you're not in the UK and not using a proxy (and not using VPN or VPS), it cannot possibly work, and is not a bug.  BBC and ITV programming are only available in the UK.  Proxies used to work, but no longer do.  Even some VPN services no longer work because the BBC blacklisted them.  Sorry, I know it's not a happy story, but it's the real story.  There are some VPN services that still work, but nobody wants to say what they are in public lest they get shut down too.  Most services have a free trial period, or even a free, but limited in bandwidth and capacity mode, so the best I can suggest is to give it a try.  You could also try a VPS service.  They can actually be cheaper but you always have to copy the files from your VPS machine back to your home machine after downloading them to the VPS machine, and it's nowhere near as convenient as using GiA with a VPN service that still works.
