### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by user182015** [GetiPlayerAutomator/get-iplayer-automator#567]
Occasionally, I cannot download some shows and it will say "Download Failed" in the Status column. It will download a small number of MBs but then will say "Initialising" before failing. This only happens with ITV Hub downloads and I am using the latest pre-release.

**Comment by blloyd78** [comment]
Something appears to have changed at ITV's end and now nothing will download.

**Comment by dinkypumpkin** [comment]
@user182015: You have provided no useful information, so this ticket has been closed. Read this before you think about creating another ticket:

https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Reporting-Issues

But before you do, understand that all downloads can be unreliable. Sometimes the problem is at the ITV end and sometimes it lies with your upstream connection. There is nothing GiA can do about either. You just have to delete any previous partial download and try again. It is highly likely you would be wasting your time and ours by creating a new ticket for this issue. 

@blloyd78: Avoid hyperbole. What you mean is the programme(s) you wanted didn't download. If you can't be bothered to provide even a single example, don't spread FUD.

**Comment by blloyd78** [comment]
The last time I supplied several examples, you also closed that thread, claiming 'hijacking'. Everything I have tried to download from ITV - including programmes I didn't want, just to prove your point for you - fail. That's not FUD.

**Comment by dinkypumpkin** [comment]
Well, you were hijacking, so what did you expect? Besides, your "several examples" in #558 were worthless. You provided the names of two series with no indication of which of the 20+ episodes wouldn't download. Unless you can provide a specific example where GiA itself isn't functioning properly, don't waste our collective bandwidth with irrelevant and incomplete posts. And it's FUD in anyone's book when you make blanket assertions such as "nothing will download" that apparently only apply to you. ITV downloads are fine here, and even the OP only reported occasional problems.

**Comment by user182015** [comment]
Sorry about not providing any examples. I'm trying to download "Britain's Got Talent" Episode 5 (Audition 5). When I use the current webpage button, it will copy it and download a few MBs of it. Then goes to Initialising RTMPDump, then Download Failed. I'm using the latest pre-release, on Mac OS X 10.11.4. I am not using a proxy (I'm in the UK).

**Comment by dinkypumpkin** [comment]
@user182015: Thanks. That programme downloads fine here. As I said, you'll just have to keep deleting the partial download and trying again. ITV servers were a bit flaky a couple of days ago, but no sign of that today, though there is no guarantee we are accessing the same servers.

**Comment by user182015** [comment]
OK. Thank you. It seems to be downloading more now. On 200MB now. Thanks a lot.
