### ISSUE TITLE
'Use Current Webpage' Stopped Working on one machine but not on another - 1.8.7 pre.3

### ISSUE THREAD

**Issue by Radar68** [GetiPlayerAutomator/get-iplayer-automator#572]
Hi,
I appreciate the build is unsupported but I was hoping to post this for anyone else who is seeing this issue plus it may well be a bug?
I have been successfully using 1.8.7 pre.3 for some time now with the Use Current Webpage to get the PID and download.
Been using this well for both iPlayer and ITVHub downloads.  No issues at all on OSX 10.11.5.
However today after downloading 2 iPlayer programmes I can no longer use this option.
Basically whether I'm on an iPlayer or ITVHub page pressing this option always pulls up the last successful iPlayer PID download I did earlier today.  I cannot get it to use the actual current webpage.
I have cleared my Safari history, reset the GiA cache and cleared the GiA download history - all to no avail.
GiA is basically 'stuck' on a previous PID and I can't seem to get it to move on anymore.  It is only affecting 1 of my 2 GiA systems (both 10.11.5), and unfortunately it's the one I use almost exclusively.  In the mean time I'm using the 2nd system for downloads.
Any help is greatly appreciated as without this app my very limited TV viewing will become almost no existent!
Radar

*** UPDATE ***
Reverting (as advised in wiki) to latest stable version 1.8.6 and issue remains.  I simply cannot progress past this last programme.  Appears there is something 'stuck' somewhere   

*** UPDATE 2 ***
I have completely removed GiA from my primary system (following Clean Install wiki) and reinstalled 1.8.7 pre.3.  issue remains.

*** UPDATE 3 ***
I am able to manually manipulate the PID of the 'Use Current Webpage' to effectively get at any iPlayer programme now, even though the problem persists when if use the function to start with.  But at least I can download iPlayer content.  I have tried 'fiddling' with the ITVHub PIDs etc but as yet I cannot get it to work so am doing ITVHub stuff on my secondary machine.

**Comment by larryy** [comment]
It's probably not the solution you want, and I hope GiA continues to be tested with Safari, but a viable workaround might be to use Chrome.  I've been having GiA grab its links from Chrome and as far as I know that is still working.  I'll try to remember to test it tonight.

**Comment by Radar68** [comment]
@larryy Thanks for taking the time to reply.
My 2nd machine is still grabbing PIDs from Safari just fine using 1.8.7 pre.3 that's what so confusing as the primary one just stopped today.
I want to avoid using Chrome at all costs as I have had concerns about it in the past and removed it.  I found that it installed software inside the El Capitan user sandboxed area (usr\local) without my knowledge or consent.  The app just appeared in Launchpad. Wasn't pleased so removed it.
I stick to using the second machine for now and see what gives for a later GiA release as and when it appears.  Who knows it may even disappear.
By all means let me have your Chrome feedback though as I really do use this app and need it to work.
Kind Regards
Radar

**Comment by dinkypumpkin** [comment]
"Use Current Webpage" still works fine with Safari in 1.8.7-pre.3, as you have demonstrated yourself by using it on a second machine. You have provided very little information to go on, but the best guess is that you somehow managed to corrupt your queue file. Try deleting whatever is "stuck" in the queue, then restart GiA and try again. If that doesn't work, quit GiA, the back up and delete:

    /Users/<username>/Library/Application Support/Get iPlayer Automator/Queue.automatorqueue

and then start GiA and try again. Be aware that Queue.automatorqueue also holds series-link entries, so you should note them down in order to restore them.

**Comment by Radar68** [comment]
Sadly deleting that file has not helped.  It gets recreated but 'Use Current Webpage' still pulls back the old iPlayer show even when on an ITVHub page in Safari.
If there is any more information I can provide that may help me then please let me know what is required.  I can reproduce in 1.8.6 on the same machine so versions seem irrelevant.
There must be some pointer somewhere that has become corrupted though as I completely removed GiA and its associate files its difficult to know what GiA is reading incorrectly or what else may be at fault outside GiA.

**Comment by dinkypumpkin** [comment]
Reverting to 1.8.6 is not diagnostic since 'Use Current Webpage' won't work for ITV in 1.8.6. Since the bogus programme doesn't appear in an empty queue until you invoke UCW, it seems clear that GiA isn't reading anything incorrectly. The queue file is the only place queue contents are stored, and that file is empty when regenerated. You can load it in a text editor to verify. My only other suggestion is to quit and restart both Safari and GiA, then try again. There may be something wrong on your machine underneath the API GiA uses to access Safari.

**Comment by Radar68** [comment]
Tried everything and still no joy I'm afraid.  Seems specific to this machine but I was hoping to at least get somewhere maybe with someone who has also seen this.
I have completely reset Safari caches and history and cookies etc.  Reset GiA restarted both.  Nada.  Still the same.  I just cannot see where GiA can be getting the information from.  Its simply not there in Safari anymore.
UCW always comes back with this blasted last iPlayer download.  Nothing can stop it it seems.  The GiA queue is empty, I don't use series link or anything like that.  I use it as a basic downloader a couple of times a week.  This Monday it all went astray on this particular Mac.
Can you think of anything else I could reset or try?

**Comment by Radar68** [comment]
Resolved! I hope.
I ran Onyx the Mac cleanup utility and ran a standard automation routine with default settings plus system cache cleanup and saved application states.
Rebooted the Mac and all is now well switching between iPlayer and ITVHub in GiA.
Not sure which of the routines cleared whatever it was causing the issue but I hope this will help others if it ever happens them.

**Comment by larryy** [comment]
Heh.  I was typing the following when your "Resolved!" post showed up.   Didn't bother to finish.  But rebooting alone has been known to solve deeply mysterious problems in the past.  It's usually not the answer, but when it is...

I doubt this will help because A) you've probably already tried it (though you haven't mentioned it), and B) I don't see how it could change anything that would matter, but in the face of a complete mystery like this I would try rebooting the machine in question.  Just to get it all out of the way I'd [do it all at once].

**Comment by Radar68** [comment]
Thanks for taking the time to help me out.  Got there in the end.
Onyx has always been a last resort of me when cleaning a system.  I'd rather do things manually and one at a time.
Given the system in question was 'only' my media server I thought I might as well see what happened when I ran Onyx and let it 'do its thing'.  I selected the system cache and application states extra to the defaults because I figured having reset Safari and reinstalled GiA then the problem must be system side so to speak.
Seems to have done something anyway and its back firing on all cylinders.
One to tuck away in the memory banks in case its needed in the future.
Thanks Again
Radar

**Comment by dinkypumpkin** [comment]
Reset of Safari would likely never be sufficient. GiA would have to get the bad URL from a misbehaving system or browser component loaded in memory, so reboot would be the cure.

**Comment by Radar68** [comment]
Reboots didn't seem to have any effect but I'm willing to believe anything at the moment.
Onyx resolved the problem for me and will be on my list of fixes should the problem reoccur.
Keep up the very good work with GiA development. It is the must have app for me with iPlayer and ITVHub.
Now if you could extend funcionality to QuestTV I'd pay handsomely for the app!......
