### ISSUE TITLE
BBC Podcast downloads queued from PVR are broken

### ISSUE THREAD

**Issue by Mac-Man-APH** [GetiPlayerAutomator/get-iplayer-automator#606]
If you select in Preferences 'Items to Cache:' BBC Podcasts tick box then PVR fails to download anything, all without any warnings. Deselect BBC Podcasts and use 'Series-Link to Queue' button and it works.

[Required information not provided by user]

**Comment by dinkypumpkin** [comment]
Podcasts are broken in get_iplayer (and thus in GiA) due to a change in BBC data feeds. There is no plan to fix the problem since podcast support is scheduled for removal from get_iplayer. It appears that at least some podcasts can be downloaded by queuing them individually from search results. Podcast downloads queued via PVR appear to be broken, however. Remove any podcasts from your Series-Link list and download them individually. If that doesn't work, leave BBC Podcasts deselected in the Items to Cache section in preferences to avoid further problems. Podcasts can be downloaded directly from the BBC Podcasts site, though many are also available as normal radio programmes in GiA.

**Comment by Mac-Man-APH** [comment]
Thanks for the info I will leave podcasts deselected.

After all your hard work developing GetPalyerAutomator I would like to make a donation, how do I do that?

Regards Alan

**Comment by dinkypumpkin** [comment]
Thanks for the offer, but I don't accept donations. GiA's original developer takes donations here:

http://tom-tech.com/iplayer_automator/iPlayer_Automator/Get_iPlayer_Automator.html
