### ISSUE TITLE
issue downloading BBC tv content

### ISSUE THREAD

**Issue by johnl1129** [GetiPlayerAutomator/get-iplayer-automator#615]
This issue just started yesterday, and I'm completely stumped by it.
Note, I haven't tested it with programs that aren't audio described, but I'd be surprised if similar results weren't seen.
As a totally blind person, I download all of my shows with the audio described option (I appreciate you including that as an option in preferences. Thanks!!) Yesterday, I noted that programs were taking longer than normal to initialize. Eventually, the progress bar moved and things seemed to download. A while later, a dialog would pop up stating none of my preferred formats were available and to add more in preferences. I added all of the formats, so that seemed odd.
The strangest thing, however, is that a copy of the program I was downloading shows up in my destination folder. However, despite having the audio description box ticked in preferences, and knowing that episodes of the shows I'm downloading have audio described versions, only the non-described versions show up in my download folder.
This happens with Doctors, Eastenders and the Doctor Blake Mysteries. Those are the only ones I've tried so far, though Casualty will populate in my download queue later tonight, and I suspect with much the same result.
Thanks in advance for any help resolving this.

**Comment by dinkypumpkin** [comment]
Selecting the audio described option doesn't mean you will get audio description in the download. It only means that an audio described file will be downloaded if one exists in the format that GiA supports. If not, the default version is downloaded. Since you didn't bother to include even one example, there is no way to check your particular claim. However, it is true that a number of audio described BBC programmes from the last few days are not available in the format supported by GiA. It could be a temporary glitch, or it could be that they have stopped using that format altogether. Your only option would be use get_iplayer itself for those programmes.
