### ISSUE TITLE
Cannot update nor send feedback/report bug in GiA

### ISSUE THREAD

**Issue by UKenGB** [GetiPlayerAutomator/get-iplayer-automator#622]
I suspect this is due to main website being down. What is happening with that? Is there a long term solution to fix GiA?

**Comment by Lordsnooty05** [comment]
I also can't submit feedback or report the bug that is definitely in GetiPlayer Automator

**Comment by woolfeyes** [comment]
Same here. PID does not exist; can't report bugs, can't update caches, can't download anything.

**Comment by Lordsnooty05** [comment]
To get the App to work:-  If you look down the other issues you will find a fix or  a way round the bug that is blighting this superb App. In the next few lines I will try and copy some of the comments that have helped me get this Application to work.....Thanks must go mostly to someone called Ghost but some others have helped. So here we go I hope it works for you as it does for me:-

First of all the reason there is this problem appears to be because the web site that provides the quick caching files is dead. It also provides software updates (there are no new updates, however), provided proxy settings, feedback handling, etc., so those are no longer working.

The way to get round this is to  go to Preferences/settings and go to quick caching(BBC Only) and UNCHECK it. then go to the Tab known as FILE and '**Force cache update**'

Also if you are in the UK don't use a proxy (Proxy = None in preferences). If you're not in the UK, you should be using a VPN instead of a proxy. I'm in the UK and I don't use a Proxy.

This has worked for me and I hope it works for you......mainly it is '**Force cache update**'

**Comment by woolfeyes** [comment]
@Lordsnooty05 Thanks a million, this worked a treat in GiA for BBC - but doesn't work for ITV, which means that GiA now has the same BBC-only coverage of GiP.. 

I've heard talk of there being an itv.plugin that should be in my ~/Library/Application Support/Get iPlayer Automator/plugins directory, but the only file there is podcast.plugin.. Does this file exist, and does it point GiA to an ITV cache / directory?

Thanks in advance.

**Comment by Lordsnooty05** [comment]
woolfeyes, I haven't a clue as I have said before I know nothing about programming or how to put n application together (there are much smarter people than me on here to sort that problem out)....hopefully someone will answer you and again there will be an easy fix for that

**Comment by dinkypumpkin** [comment]
Closed by #631
