### ISSUE TITLE
All GiA Downloads Failing

### ISSUE THREAD

**Issue by gloryglory1882** [GetiPlayerAutomator/get-iplayer-automator#625]
What steps will reproduce the problem?

Failed downloading any program.
Programs that have been successful in the past.

What is the expected output? 

Downloads to succeed

What do you see instead?

Received Warning when hitting Start button:

Invalid proxy host. Downloads may fail. Do you wish to continue?
Invalid proxy host: address=[(null)] length=0

Hit Yes to Continue and then all the Downloads Failed

Failed Download Solutions
Diagnosis
Problem Unknown
Please submit a bug report  from the application menu.

Also when trying to submit feedback:
An Error Occured
There was a problem sending your feedback.  Please try again at another time

In addition to these issues the program is also having problems finding things that a few days ago it could find easily.

What version of GiA are you using? On what version of OS X?
Version 1.8.7 (1793)
OS 10.11.3 (15D21)

Are you using a web proxy? DNS proxy? VPN? VPS?
Not that I’m aware of.

What programme are you attempting to download? 

Storyville - Exposed: Magicians, Psychics and Frauds
(I would actually prefer to download the most recent Storyville however this one that I’ve listed above is very old, I do not wish to download this one but am using it as an example of GiA not working)

Verbose log of the attempt:

Get iPlayer Automator 1.8.7 Initialized.

AppController: Updating Program Index Feeds...

AppController: Index was Up-To-Date.

INFO: Loading proxy settings...
INFO: Loading provided proxy (may take up to 20 seconds)...
INFO: Proxy load complete.
WARNING: Invalid proxy host: address=(null) length=0
INFO: Using proxy: (null)

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=b04ndsb3): Downloading Storyville - Exposed: Magicians, Psychics and Frauds
INFO: encodinglocale = UTF-8
INFO: encodinglocalefs = UTF-8
INFO: encodingconsoleout = UTF-8
INFO: encodingconsolein = UTF-8
INFO: ${^UNICODE} = 39
INFO: User prefs dir: /Users/doug/Library/Application Support/Get iPlayer Automator
INFO: System options dir: /etc/get_iplayer/options
INFO: Using Proxy (null)
	versionlist = default
INFO: Search args: ''
INFO: Will try prog types: tv
INFO: Loaded history for first check.
INFO: Loading recordings history
INFO: Programme not in history
INFO: Got 1683 file cache entries for tv
INFO: pid found in cache
BBC Download (ID=b04ndsb3): Storyville - Exposed: Magicians, Psychics and Frauds Failed

AppController: Downloads Finished

Please provide any additional information below:

Is it related to this issue?
'No shows found' / 'Unknown: PID Not Found' (BBC) to 'No shows found' (BBC) / 'Unknown: PID Not Found' / Web site down / Software updates broken/ Everything else that is wrong with GiA
https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues/617
@dantellocy commented 6 days ago • edited by dinkypumpkin
“EDIT3: This will not be fixed until GiA's developer resuscitates the web site. It may be dead for good - there is no way to know.”

**Comment by Lordsnooty05** [comment]
I have the same problem......Is this application down for good? That would be terrible news

**Comment by DarthVivid** [comment]
I'm getting this also. My Macbook Air says 

Invalid proxy host. Downloads may fail. Do you wish to continue?
Invalid proxy host: address=[(null)] length=0

My iMac says Unknown Pid Not found. 

Quite frustrating. Hadn't used for a while & now it seems to be dead :(

**Comment by Lordsnooty05** [comment]
DarthVivid  If you look down the other issues you will find a fix or way round the bug that is blighting this superb App. In the next few lines I will try and copy some of the comments that have helped me get this Application to work.....Thanks must go mostly to someone called Ghost but some others have helped. So here we go I hope it works for you as it does for me:-

First of all the reason there is this problem appears to be because the web site that provides the quick caching files is dead. It also provides software updates (there are no new updates, however), provided proxy settings, feedback handling, etc., so those are no longer working.

The way to get round this is to  go to Preferences/settings and go to quick caching(BBC Only) and UNCHECK it. then go to the Tab known as FILE and '**Force cache update**'

Also if you are in the UK don't use a proxy (Proxy = None in preferences). If you're not in the UK, you should be using a VPN instead of a proxy. I'm in the UK and I don't use a Proxy.

This has worked for me and I hope it works for you......mainly it is '**Force cache update**'

**Comment by DarthVivid** [comment]
Lordsnooty05 you're my hero! Changed these settings & I'm now downloading again. Thank you very much :)

**Comment by Lordsnooty05** [comment]
DarthVivid....thanks for coming back and letting me know that it is working for you. Maybe it would be a good idea if the person that is looking after this Forum should either repeat my Fix on the other issues or write their own Fix so that everyone that uses this Great Application has a way round the problems. My problem in the future is this may eventually not work until the Developer gets his Website up and running or he may never get it up and running again.....which would be a terrible shame. I don't know anything about programming but  I'm sure there are very smart people out there who could help take this App on and make it work....I hope they do as I use this App every day. Happy Easter

**Comment by Lucky-me** [comment]
Big thanks to Lordsnooty05 - my problem solved - same as Gloryglory1882.  Big time waster for a couple of weeks after GiA been working well for a longtime.

Opened one iPlayer programme in browser then hit 'use web page' as usual.  Programme was immediatelyrecognised OK but when hitting Start got error message:  Invalid proxy host. Downloads may fail. Do you wish to continue?   Also Invalid proxy host: address=[(null)] length=0.

Refused to download.

Already sent a bug report about this some time ago but no reply.  Today it was repeatedly impossible to send a bug report - got error message:  There was a problem sending your feedback. Please try again at another time.  That was the last straw until I stumbled on this forum and the solution.  Thanks again.

**Comment by Lordsnooty05** [comment]
Lucky-me.....sorry to hear that GIA isn't work for you. Let me just say that I know nothing about programming or anything like that. Anything that I am saying is only what I have gleamed from this forum and what works for me. First of all GIA is working for me.....not as well as it did but it is working. So the only thing I can do for you is explain what I do to make GIA work OK?
I open GIA
I immediately go to the Tabs and click on **FILE** and then down to **FORCE CACHE UPDATE** I also go and open up **Preferences** and go to **GENERAL** Tab and make certain that **Proxy** is set at **None** and open Tab known as **ADVANCED** and make certain that **"Test Proxy before Download"** is unticked. The I open Safari and go to the Programme I want to record and then click on **USE CURRENT WEBPAGE** and then click on **START**
As I have said before this works for me. Why not try it and if it doesn't work can you let me know programme you are trying to record and I will try and do it for you and if I can get it working I can try and send it to you. Let me know how you get on.

**Comment by Lucky-me** [comment]
Lordsnooty05 - you have misunderstood!

After my problems I altered the settings exactly as you recommended.  That has made it work OK again!

Problem solved - that's why I provided my thanks to you.

**Comment by Lordsnooty05** [comment]
Sorry yes I did misunderstand. It's just when said that you trying repeatly to send a bug report your problem hadn't been fixed. So I'm glad it is fixed .......no harm done because others can use my work around, glad to be of service. Does anyone know if we will ever get GIA back to what we know and love? Has anyone contacted the developer if this app to see how they are or does anyone know how to fix this app? Anyone, know anything about what is happening?
Thanks as usual for a Superb App

**Comment by danielavdh** [comment]
Super, thanks!!!

**Comment by dinkypumpkin** [comment]
Closed by #631
